export const FakeItems: FakeItem[] = [
  {
    src: '/fake-items/teddy-bear.png',
    dx: 450,
    dy: 400,
    width: 66,
    height: 66,
    description: 'Its a cute teddy bear.'
  },
  {
    src: '/fake-items/blanket.png',
    dx: 30,
    dy: 350,
    width: 77,
    height: 77,
    description: 'This is just a blanket.'
  },
]

export const RealItems: RealItem[] = [
  {
    id: 0,
    name: 'blueberry',
    src: '/real-items/blueberry.png', 
    dx: 160,
    dy: 605,
    width: 28, 
    height: 28, 
    isVisible: true,
    isCorrect: false,
    hint: 'Enter the correct answer (ans: 001)',
    completionMessage: 'Find the next fruit.',
    type: 'quiz',
    answer: '001',
    unlockedPrerequisite: null,
  },
  {
    id: 1,
    name: 'cherry',
    src: '/real-items/cherry.png', 
    dx: 520,
    dy: 560,
    width: 28, 
    height: 28, 
    isVisible: false,
    isCorrect: false,
    hint: 'Great work! Find the last fruit.',
    completionMessage: 'Find the last fruit.',
    type: 'click',
    unlockedPrerequisite: null,
  },
  {
    id: 2,
    name: 'raspberry',
    src: '/real-items/raspberry.png', 
    dx: 200,
    dy: 171,
    width: 28, 
    height: 28, 
    isVisible: false,
    isCorrect: false,
    hint: 'Be careful! Protect your hands from the cactus.',
    completionMessage: 'Congrats! You have complete all tasks, find the car key and leave the house.',
    type: 'prerequisite',
    prerequisiteItem: 'rubber-gloves',
    unlockedPrerequisite: 1,
  },
  {
    id: 3,
    name: 'transportation',
    src: '/real-items/transportation.png', 
    dx: 448,
    dy: 150,
    width: 44, 
    height: 44, 
    isVisible: false,
    isCorrect: false,
    hint: 'You need the key to start the engine.',
    completionMessage: 'You have successfully escaped from this room!',
    type: 'prerequisite',
    prerequisiteItem: 'key',
    unlockedPrerequisite: null,
  },
]

export const PrerequisiteItems: PrerequisiteItem[] = [
  {
    id: 0,
    name: 'rubber-gloves',
    src: '/inventory-items/rubber-gloves.png',
    dx: 160,
    dy: 490,
    width: 44,
    height: 44,
    description: 'These will protect your hands!',
    isVisible: true,
    inInventory: false,
  },
  {
    id: 1,
    name: 'key',
    src: '/inventory-items/key.png',
    dx: 80,
    dy: 472,
    width: 22,
    height: 22,
    description: `You've found the car key!`,
    isVisible: false,
    inInventory: false,
  }
]