export const FakeItems: FakeItem[] = [
  {
    className: 'absolute bottom-[210px] right-[190px]',
    src: '/fake-items/teddy-bear.png',
    width: 66,
    height: 66,
    alt: 'pillow',
    description: 'Its a cute teddy bear.'
  },
  {
    className: 'absolute bottom-[265px] left-[30px]',
    src: '/fake-items/blanket.png',
    width: 77,
    height: 77,
    alt: 'chef-knife',
    description: 'This is just a blanket.'
  },
]

export const RealItems: RealItem[] = [
  {
    id: 0,
    name: 'blueberry',
    className: 'absolute bottom-[60px] left-[160px]',
    scr: '/real-items/blueberry.png', 
    width: 28, 
    height: 28, 
    alt: 'blueberry(first hint)',
    isVisible: true,
    isCorrect: false,
    description: 'Enter the correct answer (ans: 001)',
    conditionalDescription: 'Find the next fruit.',
    type: 'quiz',
    ans: '001',
    prerequisiteName: null,
    realTarget: 1,
    prerequisiteTarget: null,
  },
  {
    id: 1,
    name: 'cherry',
    className: 'absolute bottom-[120px] right-[150px]',
    scr: '/real-items/cherry.png', 
    width: 28, 
    height: 28, 
    alt: 'cherry(second hint)',
    isVisible: false,
    isCorrect: false,
    description: 'Great work! Find the last fruit.',
    conditionalDescription: 'Find the last fruit.',
    type: 'click',
    ans: '',
    prerequisiteName: null,
    realTarget: 2,
    prerequisiteTarget: null,
  },
  {
    id: 2,
    name: 'raspberry',
    className: 'absolute top-[150px] left-[200px]',
    scr: '/real-items/raspberry.png', 
    width: 28, 
    height: 28, 
    alt: 'raspberry(third hint)',
    isVisible: false,
    isCorrect: false,
    description: 'Be careful! Protect your hands from the cactus.',
    conditionalDescription: 'Congrats! You have complete all tasks, find the car key and leave the house.',
    type: 'prerequisite',
    ans: '',
    prerequisiteName: 'rubber-gloves',
    realTarget: 3,
    prerequisiteTarget: 1,
  },
  {
    id: 3,
    name: 'transportation',
    className: 'absolute top-[150px] right-[220px]',
    scr: '/real-items/transportation.png', 
    width: 44, 
    height: 44, 
    alt: 'transportation(first hint)',
    isVisible: false,
    isCorrect: false,
    description: 'You need the key to start the engine.',
    conditionalDescription: 'You have successfully escaped from this room!',
    type: 'prerequisite',
    ans: '',
    prerequisiteName: 'key',
    realTarget: null,
    prerequisiteTarget: null,
  },
]

export const PrerequisiteItems: PrerequisiteItem[] = [
  {
    id: 0,
    name: 'rubber-gloves',
    className:'absolute bottom-[160px] left-[160px]',
    scr: '/inventory-items/rubber-gloves.png',
    width: 44,
    height: 44,
    alt: 'rubber glove',
    isVisible: true,
    inInventory: false,
    description: 'These will protect your hands!'
  },
  {
    id: 1,
    name: 'key',
    className: 'absolute bottom-[205px] left-[80px]',
    scr: '/inventory-items/key.png',
    width: 22,
    height: 22,
    alt: 'key',
    isVisible: false,
    inInventory: false,
    description: `You've found the car key!`,
  }
]